version: 1.0.0.{build}
configuration: Release

clone_depth: 50
os: Visual Studio 2015

before_build:
  - ps: cd Source
  - nuget restore

build:
  project: Source\Conduit.sln
  parallel: true
  verbosity: minimal
